export const AJAX_INTERCEPTOR_PROJECTS = "mock_serverity_projects"
export const AJAX_INTERCEPTOR_CURRENT_PROJECT = "mock_serverity_current_project"
export const AJAX_INTERCEPTOR_SETTINGS = "mock_serverity_settings"
export const CUSTOM_EVENT_NAME = "mock_serverity_event"
export const INJECT_ELEMENT_ID = "mock_serverity"
